# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import demoPass_pb2 as demoPass__pb2


class demoPassStub(object):
    """demo pass Service 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLoopInfo = channel.unary_unary(
                '/demopass.demoPass/getLoopInfo',
                request_serializer=demoPass__pb2.Command.SerializeToString,
                response_deserializer=demoPass__pb2.loopInfo.FromString,
                )


class demoPassServicer(object):
    """demo pass Service 
    """

    def getLoopInfo(self, request, context):
        """RPC function to send Inference graph data and receive color data for codegen
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_demoPassServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLoopInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.getLoopInfo,
                    request_deserializer=demoPass__pb2.Command.FromString,
                    response_serializer=demoPass__pb2.loopInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demopass.demoPass', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class demoPass(object):
    """demo pass Service 
    """

    @staticmethod
    def getLoopInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demopass.demoPass/getLoopInfo',
            demoPass__pb2.Command.SerializeToString,
            demoPass__pb2.loopInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
