# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import example_pb2 as example__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class PosetRLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getEmbedding = channel.unary_unary(
                '/posetrl.PosetRL/getEmbedding',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=example__pb2.EmbeddingResponse.FromString,
                )
        self.applyAction = channel.unary_unary(
                '/posetrl.PosetRL/applyAction',
                request_serializer=example__pb2.ActionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.applyActionGetEmbeddings = channel.unary_unary(
                '/posetrl.PosetRL/applyActionGetEmbeddings',
                request_serializer=example__pb2.ActionRequest.SerializeToString,
                response_deserializer=example__pb2.EmbeddingResponse.FromString,
                )


class PosetRLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def applyAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def applyActionGetEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PosetRLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.getEmbedding,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=example__pb2.EmbeddingResponse.SerializeToString,
            ),
            'applyAction': grpc.unary_unary_rpc_method_handler(
                    servicer.applyAction,
                    request_deserializer=example__pb2.ActionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'applyActionGetEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.applyActionGetEmbeddings,
                    request_deserializer=example__pb2.ActionRequest.FromString,
                    response_serializer=example__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'posetrl.PosetRL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PosetRL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/posetrl.PosetRL/getEmbedding',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            example__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def applyAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/posetrl.PosetRL/applyAction',
            example__pb2.ActionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def applyActionGetEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/posetrl.PosetRL/applyActionGetEmbeddings',
            example__pb2.ActionRequest.SerializeToString,
            example__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
