# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='posetrl',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\x12\x07posetrl\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"\x1f\n\rActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32\xe2\x01\n\x07PosetRL\x12\x44\n\x0cgetEmbedding\x12\x16.google.protobuf.Empty\x1a\x1a.posetrl.EmbeddingResponse\"\x00\x12?\n\x0b\x61pplyAction\x12\x16.posetrl.ActionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12P\n\x18\x61pplyActionGetEmbeddings\x12\x16.posetrl.ActionRequest\x1a\x1a.posetrl.EmbeddingResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_EMBEDDINGRESPONSE = _descriptor.Descriptor(
  name='EmbeddingResponse',
  full_name='posetrl.EmbeddingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='embedding', full_name='posetrl.EmbeddingResponse.embedding', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=93,
)


_ACTIONREQUEST = _descriptor.Descriptor(
  name='ActionRequest',
  full_name='posetrl.ActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='posetrl.ActionRequest.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['EmbeddingResponse'] = _EMBEDDINGRESPONSE
DESCRIPTOR.message_types_by_name['ActionRequest'] = _ACTIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmbeddingResponse = _reflection.GeneratedProtocolMessageType('EmbeddingResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGRESPONSE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:posetrl.EmbeddingResponse)
  })
_sym_db.RegisterMessage(EmbeddingResponse)

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONREQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:posetrl.ActionRequest)
  })
_sym_db.RegisterMessage(ActionRequest)



_POSETRL = _descriptor.ServiceDescriptor(
  name='PosetRL',
  full_name='posetrl.PosetRL',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=129,
  serialized_end=355,
  methods=[
  _descriptor.MethodDescriptor(
    name='getEmbedding',
    full_name='posetrl.PosetRL.getEmbedding',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_EMBEDDINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='applyAction',
    full_name='posetrl.PosetRL.applyAction',
    index=1,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='applyActionGetEmbeddings',
    full_name='posetrl.PosetRL.applyActionGetEmbeddings',
    index=2,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_EMBEDDINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSETRL)

DESCRIPTOR.services_by_name['PosetRL'] = _POSETRL

# @@protoc_insertion_point(module_scope)
