# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegisterAllocation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RegisterAllocation.proto',
  package='registerallocation',
  syntax='proto3',
  serialized_options=b'\n#io.grpc.examples.registerallocationB\027RegisterAllocationProtoP\001\242\002\003REG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18RegisterAllocation.proto\x12\x12registerallocation\"+\n\x04Path\x12\x0e\n\x06IRPath\x18\x01 \x01(\t\x12\x13\n\x0bSeedEmbPath\x18\x02 \x01(\t\"\x1c\n\tGraphList\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x88\x02\n\x13RegisterProfileList\x12H\n\x07regProf\x18\x01 \x03(\x0b\x32\x37.registerallocation.RegisterProfileList.RegisterProfile\x12\x0e\n\x06result\x18\x02 \x01(\x08\x1a\x96\x01\n\x0fRegisterProfile\x12\r\n\x05regID\x18\x01 \x01(\r\x12\x13\n\x0bspillWeight\x18\x02 \x01(\x02\x12\x15\n\rinterferences\x18\x03 \x03(\r\x12\x14\n\x0cuseDistances\x18\x04 \x03(\r\x12\x12\n\nsplitSlots\x18\x05 \x03(\r\x12\x1e\n\x16positionalSpillWeights\x18\x06 \x03(\x02\"\x94\x01\n\x04\x44\x61ta\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06regidx\x18\x02 \x01(\r\x12\x0f\n\x07payload\x18\x03 \x01(\x03\x12\x31\n\x05\x63olor\x18\x04 \x03(\x0b\x32\".registerallocation.Data.colorData\x1a\'\n\tcolorData\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"\x07\n\x05\x45mpty2\xac\x01\n\x12RegisterAllocation\x12\x46\n\tgetGraphs\x12\x18.registerallocation.Path\x1a\x1d.registerallocation.GraphList\"\x00\x12N\n\x07\x63odeGen\x12\x18.registerallocation.Data\x1a\'.registerallocation.RegisterProfileList\"\x00\x42\x46\n#io.grpc.examples.registerallocationB\x17RegisterAllocationProtoP\x01\xa2\x02\x03REGb\x06proto3'
)




_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='registerallocation.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='IRPath', full_name='registerallocation.Path.IRPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SeedEmbPath', full_name='registerallocation.Path.SeedEmbPath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=91,
)


_GRAPHLIST = _descriptor.Descriptor(
  name='GraphList',
  full_name='registerallocation.GraphList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='registerallocation.GraphList.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=121,
)


_REGISTERPROFILELIST_REGISTERPROFILE = _descriptor.Descriptor(
  name='RegisterProfile',
  full_name='registerallocation.RegisterProfileList.RegisterProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regID', full_name='registerallocation.RegisterProfileList.RegisterProfile.regID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spillWeight', full_name='registerallocation.RegisterProfileList.RegisterProfile.spillWeight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interferences', full_name='registerallocation.RegisterProfileList.RegisterProfile.interferences', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='useDistances', full_name='registerallocation.RegisterProfileList.RegisterProfile.useDistances', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='splitSlots', full_name='registerallocation.RegisterProfileList.RegisterProfile.splitSlots', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positionalSpillWeights', full_name='registerallocation.RegisterProfileList.RegisterProfile.positionalSpillWeights', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=388,
)

_REGISTERPROFILELIST = _descriptor.Descriptor(
  name='RegisterProfileList',
  full_name='registerallocation.RegisterProfileList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regProf', full_name='registerallocation.RegisterProfileList.regProf', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='registerallocation.RegisterProfileList.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REGISTERPROFILELIST_REGISTERPROFILE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=388,
)


_DATA_COLORDATA = _descriptor.Descriptor(
  name='colorData',
  full_name='registerallocation.Data.colorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='registerallocation.Data.colorData.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='registerallocation.Data.colorData.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=539,
)

_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='registerallocation.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='registerallocation.Data.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regidx', full_name='registerallocation.Data.regidx', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='registerallocation.Data.payload', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='registerallocation.Data.color', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DATA_COLORDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=539,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='registerallocation.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=548,
)

_REGISTERPROFILELIST_REGISTERPROFILE.containing_type = _REGISTERPROFILELIST
_REGISTERPROFILELIST.fields_by_name['regProf'].message_type = _REGISTERPROFILELIST_REGISTERPROFILE
_DATA_COLORDATA.containing_type = _DATA
_DATA.fields_by_name['color'].message_type = _DATA_COLORDATA
DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['GraphList'] = _GRAPHLIST
DESCRIPTOR.message_types_by_name['RegisterProfileList'] = _REGISTERPROFILELIST
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), {
  'DESCRIPTOR' : _PATH,
  '__module__' : 'RegisterAllocation_pb2'
  # @@protoc_insertion_point(class_scope:registerallocation.Path)
  })
_sym_db.RegisterMessage(Path)

GraphList = _reflection.GeneratedProtocolMessageType('GraphList', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHLIST,
  '__module__' : 'RegisterAllocation_pb2'
  # @@protoc_insertion_point(class_scope:registerallocation.GraphList)
  })
_sym_db.RegisterMessage(GraphList)

RegisterProfileList = _reflection.GeneratedProtocolMessageType('RegisterProfileList', (_message.Message,), {

  'RegisterProfile' : _reflection.GeneratedProtocolMessageType('RegisterProfile', (_message.Message,), {
    'DESCRIPTOR' : _REGISTERPROFILELIST_REGISTERPROFILE,
    '__module__' : 'RegisterAllocation_pb2'
    # @@protoc_insertion_point(class_scope:registerallocation.RegisterProfileList.RegisterProfile)
    })
  ,
  'DESCRIPTOR' : _REGISTERPROFILELIST,
  '__module__' : 'RegisterAllocation_pb2'
  # @@protoc_insertion_point(class_scope:registerallocation.RegisterProfileList)
  })
_sym_db.RegisterMessage(RegisterProfileList)
_sym_db.RegisterMessage(RegisterProfileList.RegisterProfile)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {

  'colorData' : _reflection.GeneratedProtocolMessageType('colorData', (_message.Message,), {
    'DESCRIPTOR' : _DATA_COLORDATA,
    '__module__' : 'RegisterAllocation_pb2'
    # @@protoc_insertion_point(class_scope:registerallocation.Data.colorData)
    })
  ,
  'DESCRIPTOR' : _DATA,
  '__module__' : 'RegisterAllocation_pb2'
  # @@protoc_insertion_point(class_scope:registerallocation.Data)
  })
_sym_db.RegisterMessage(Data)
_sym_db.RegisterMessage(Data.colorData)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'RegisterAllocation_pb2'
  # @@protoc_insertion_point(class_scope:registerallocation.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_REGISTERALLOCATION = _descriptor.ServiceDescriptor(
  name='RegisterAllocation',
  full_name='registerallocation.RegisterAllocation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=551,
  serialized_end=723,
  methods=[
  _descriptor.MethodDescriptor(
    name='getGraphs',
    full_name='registerallocation.RegisterAllocation.getGraphs',
    index=0,
    containing_service=None,
    input_type=_PATH,
    output_type=_GRAPHLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='codeGen',
    full_name='registerallocation.RegisterAllocation.codeGen',
    index=1,
    containing_service=None,
    input_type=_DATA,
    output_type=_REGISTERPROFILELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTERALLOCATION)

DESCRIPTOR.services_by_name['RegisterAllocation'] = _REGISTERALLOCATION

# @@protoc_insertion_point(module_scope)
