# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegisterAllocationInference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RegisterAllocationInference.proto',
  package='registerallocationinference',
  syntax='proto3',
  serialized_options=b'\n,io.grpc.examples.registerallocationinferenceB RegisterAllocationInferenceProtoP\001\242\002\003REG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!RegisterAllocationInference.proto\x12\x1bregisterallocationinference\"\x1c\n\tGraphList\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\xce\x03\n\x13RegisterProfileList\x12Q\n\x07regProf\x18\x01 \x03(\x0b\x32@.registerallocationinference.RegisterProfileList.RegisterProfile\x12\x10\n\x08\x66uncName\x18\x02 \x01(\t\x12\x10\n\x08\x66ileName\x18\x03 \x01(\t\x12\r\n\x05\x66unid\x18\x04 \x01(\r\x12\x0e\n\x06result\x18\x05 \x01(\x08\x12\x0b\n\x03new\x18\x06 \x01(\x08\x1a\x15\n\x06vector\x12\x0b\n\x03vec\x18\x01 \x03(\x01\x1a\xfc\x01\n\x0fRegisterProfile\x12\r\n\x05regID\x18\x01 \x01(\r\x12\r\n\x05\x63olor\x18\x02 \x01(\r\x12\x13\n\x0bspillWeight\x18\x03 \x01(\x02\x12\x0b\n\x03\x63ls\x18\x04 \x01(\t\x12\x12\n\nsplitSlots\x18\x05 \x03(\r\x12\x15\n\rinterferences\x18\x06 \x03(\r\x12\x14\n\x0cuseDistances\x18\x07 \x03(\r\x12\x1e\n\x16positionalSpillWeights\x18\x08 \x03(\x02\x12H\n\x07vectors\x18\t \x03(\x0b\x32\x37.registerallocationinference.RegisterProfileList.vector\"\xaf\x01\n\x04\x44\x61ta\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06regidx\x18\x02 \x01(\r\x12\x0f\n\x07payload\x18\x03 \x01(\x03\x12\x10\n\x08\x66uncName\x18\x04 \x01(\t\x12:\n\x05\x63olor\x18\x05 \x03(\x0b\x32+.registerallocationinference.Data.colorData\x1a\'\n\tcolorData\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"\x07\n\x05\x45mpty2\x7f\n\x1bRegisterAllocationInference\x12`\n\x07getInfo\x12\x30.registerallocationinference.RegisterProfileList\x1a!.registerallocationinference.Data\"\x00\x42X\n,io.grpc.examples.registerallocationinferenceB RegisterAllocationInferenceProtoP\x01\xa2\x02\x03REGb\x06proto3'
)




_GRAPHLIST = _descriptor.Descriptor(
  name='GraphList',
  full_name='registerallocationinference.GraphList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='registerallocationinference.GraphList.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=94,
)


_REGISTERPROFILELIST_VECTOR = _descriptor.Descriptor(
  name='vector',
  full_name='registerallocationinference.RegisterProfileList.vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vec', full_name='registerallocationinference.RegisterProfileList.vector.vec', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=304,
)

_REGISTERPROFILELIST_REGISTERPROFILE = _descriptor.Descriptor(
  name='RegisterProfile',
  full_name='registerallocationinference.RegisterProfileList.RegisterProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regID', full_name='registerallocationinference.RegisterProfileList.RegisterProfile.regID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='registerallocationinference.RegisterProfileList.RegisterProfile.color', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spillWeight', full_name='registerallocationinference.RegisterProfileList.RegisterProfile.spillWeight', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cls', full_name='registerallocationinference.RegisterProfileList.RegisterProfile.cls', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='splitSlots', full_name='registerallocationinference.RegisterProfileList.RegisterProfile.splitSlots', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interferences', full_name='registerallocationinference.RegisterProfileList.RegisterProfile.interferences', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='useDistances', full_name='registerallocationinference.RegisterProfileList.RegisterProfile.useDistances', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positionalSpillWeights', full_name='registerallocationinference.RegisterProfileList.RegisterProfile.positionalSpillWeights', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vectors', full_name='registerallocationinference.RegisterProfileList.RegisterProfile.vectors', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=559,
)

_REGISTERPROFILELIST = _descriptor.Descriptor(
  name='RegisterProfileList',
  full_name='registerallocationinference.RegisterProfileList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regProf', full_name='registerallocationinference.RegisterProfileList.regProf', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='funcName', full_name='registerallocationinference.RegisterProfileList.funcName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileName', full_name='registerallocationinference.RegisterProfileList.fileName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='funid', full_name='registerallocationinference.RegisterProfileList.funid', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='registerallocationinference.RegisterProfileList.result', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new', full_name='registerallocationinference.RegisterProfileList.new', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REGISTERPROFILELIST_VECTOR, _REGISTERPROFILELIST_REGISTERPROFILE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=559,
)


_DATA_COLORDATA = _descriptor.Descriptor(
  name='colorData',
  full_name='registerallocationinference.Data.colorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='registerallocationinference.Data.colorData.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='registerallocationinference.Data.colorData.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=698,
  serialized_end=737,
)

_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='registerallocationinference.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='registerallocationinference.Data.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regidx', full_name='registerallocationinference.Data.regidx', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='registerallocationinference.Data.payload', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='funcName', full_name='registerallocationinference.Data.funcName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='registerallocationinference.Data.color', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DATA_COLORDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=737,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='registerallocationinference.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=739,
  serialized_end=746,
)

_REGISTERPROFILELIST_VECTOR.containing_type = _REGISTERPROFILELIST
_REGISTERPROFILELIST_REGISTERPROFILE.fields_by_name['vectors'].message_type = _REGISTERPROFILELIST_VECTOR
_REGISTERPROFILELIST_REGISTERPROFILE.containing_type = _REGISTERPROFILELIST
_REGISTERPROFILELIST.fields_by_name['regProf'].message_type = _REGISTERPROFILELIST_REGISTERPROFILE
_DATA_COLORDATA.containing_type = _DATA
_DATA.fields_by_name['color'].message_type = _DATA_COLORDATA
DESCRIPTOR.message_types_by_name['GraphList'] = _GRAPHLIST
DESCRIPTOR.message_types_by_name['RegisterProfileList'] = _REGISTERPROFILELIST
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphList = _reflection.GeneratedProtocolMessageType('GraphList', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHLIST,
  '__module__' : 'RegisterAllocationInference_pb2'
  # @@protoc_insertion_point(class_scope:registerallocationinference.GraphList)
  })
_sym_db.RegisterMessage(GraphList)

RegisterProfileList = _reflection.GeneratedProtocolMessageType('RegisterProfileList', (_message.Message,), {

  'vector' : _reflection.GeneratedProtocolMessageType('vector', (_message.Message,), {
    'DESCRIPTOR' : _REGISTERPROFILELIST_VECTOR,
    '__module__' : 'RegisterAllocationInference_pb2'
    # @@protoc_insertion_point(class_scope:registerallocationinference.RegisterProfileList.vector)
    })
  ,

  'RegisterProfile' : _reflection.GeneratedProtocolMessageType('RegisterProfile', (_message.Message,), {
    'DESCRIPTOR' : _REGISTERPROFILELIST_REGISTERPROFILE,
    '__module__' : 'RegisterAllocationInference_pb2'
    # @@protoc_insertion_point(class_scope:registerallocationinference.RegisterProfileList.RegisterProfile)
    })
  ,
  'DESCRIPTOR' : _REGISTERPROFILELIST,
  '__module__' : 'RegisterAllocationInference_pb2'
  # @@protoc_insertion_point(class_scope:registerallocationinference.RegisterProfileList)
  })
_sym_db.RegisterMessage(RegisterProfileList)
_sym_db.RegisterMessage(RegisterProfileList.vector)
_sym_db.RegisterMessage(RegisterProfileList.RegisterProfile)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {

  'colorData' : _reflection.GeneratedProtocolMessageType('colorData', (_message.Message,), {
    'DESCRIPTOR' : _DATA_COLORDATA,
    '__module__' : 'RegisterAllocationInference_pb2'
    # @@protoc_insertion_point(class_scope:registerallocationinference.Data.colorData)
    })
  ,
  'DESCRIPTOR' : _DATA,
  '__module__' : 'RegisterAllocationInference_pb2'
  # @@protoc_insertion_point(class_scope:registerallocationinference.Data)
  })
_sym_db.RegisterMessage(Data)
_sym_db.RegisterMessage(Data.colorData)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'RegisterAllocationInference_pb2'
  # @@protoc_insertion_point(class_scope:registerallocationinference.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_REGISTERALLOCATIONINFERENCE = _descriptor.ServiceDescriptor(
  name='RegisterAllocationInference',
  full_name='registerallocationinference.RegisterAllocationInference',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=748,
  serialized_end=875,
  methods=[
  _descriptor.MethodDescriptor(
    name='getInfo',
    full_name='registerallocationinference.RegisterAllocationInference.getInfo',
    index=0,
    containing_service=None,
    input_type=_REGISTERPROFILELIST,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTERALLOCATIONINFERENCE)

DESCRIPTOR.services_by_name['RegisterAllocationInference'] = _REGISTERALLOCATIONINFERENCE

# @@protoc_insertion_point(module_scope)
