name: Build and Tests

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
    - '**.cpp'
    - '**.h'
    - '**.py'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install LLVM-10
      run: |
        wget https://apt.llvm.org/llvm.sh
        sudo bash llvm.sh 10
    - uses: actions/checkout@v3
    - name: Setup Conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge,bioconda,defaults
        auto-activate-base: true
        activate-environment: mlbridge
        environment-file: mlbridge.yml
    - name: Install other dependencies and build
      run: bash .github/workflows/mlbridge_build.sh release
    - uses: actions/upload-artifact@v2
      with:
        name: MLCompilerBridge
        path: |
          install/lib
          install/include

  test:
      runs-on: ubuntu-20.04
      needs: build
      steps:
      - name: Run Tests
        run: |
          cd test
          bash mlbridge-test.sh
